server:
  port: 8080

spring:
  application:
    name: Cloud-File-Storage

  # Using local db for development purposes
  datasource:
    url: jdbc:postgresql://localhost:5432/cfs
    username: "myuser"
    password: "secret"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: boot
      password: spring

  # Google cloud storage config
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      credentials:
        location: classpath:gcp/gcp-key.json

      storage:
        bucket: ${GCP_STORAGE_BUCKET_NAME}

# Default Admin User Configuration
# These credentials are used to create the initial admin account on startup.
admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASS}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
